name: Auction Sniper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-auction-sniper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download historical auctions database
        uses: actions/download-artifact@v4
        with:
          name: auctions-db
          path: .
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run auction sniper script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python process_auctions.py

      - name: Upload updated auctions database
        uses: actions/upload-artifact@v4
        with:
          name: auctions-db
          path: auctions.db
