name: Auction Sniper

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-auction-sniper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore SQLite database cache
        uses: actions/cache@v3
        with:
          path: auctions.db
          key: auctions-db-cache
          restore-keys: |
            auctions-db-cache
        continue-on-error: true

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run auction sniper script
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python sniper.py

      - name: Save updated SQLite database to cache
        uses: actions/cache@v3
        with:
          path: auctions.db
          key: auctions-db-cache
