name: Blizzard Data Gathering

on:
  schedule:
    - cron: '0 0 * * *'  # once per day for now
  workflow_dispatch:

jobs:
  gather:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run data gathering script
        env:
          BLIZZARD_CLIENT_ID: ${{ secrets.BLIZZARD_CLIENT_ID }}
          BLIZZARD_CLIENT_SECRET: ${{ secrets.BLIZZARD_CLIENT_SECRET }}
        run: python auctionDataRequest.py
      - name: Commit and push changes
        run: |
          set -e  # Exit script on any command failure
      
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git config pull.rebase true  # Rebase
      
          git add data/
          
          # Commit only if there are changes
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Updated Leaderboard data"
          fi
      
          # Pull latest changes, fail only on actual errors
          if ! git pull --rebase; then
            echo "Error during git pull" >&2
            exit 1
          fi
      
          # Push changes, fail if there's an actual error
          if ! git push; then
            echo "Error during git push" >&2
            exit 1
          fi

